name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  release:
    types: [ published ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: loqalabs/loqa-hub

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  test:
    name: Test & Lint with NATS
    uses: loqalabs/.github/.github/workflows/go-test.yml@main
    with:
      go-version: '1.23.0'
      proto-repo: 'loqalabs/loqa-proto'
      coverage-flag: 'loqa-hub'
      coverage-name: 'loqa-hub'

  mod-check:
    name: Validate Go Modules
    needs: test
    uses: loqalabs/.github/.github/workflows/go-mod-check.yml@main
    with:
      go-version: '1.23.0'

  build:
    name: Build Go Binary
    needs: mod-check
    uses: loqalabs/.github/.github/workflows/go-build.yml@main
    with:
      go-version: '1.23.0'
      binary-name: 'loqa-hub'

  security:
    name: Security Analysis
    needs: build
    uses: loqalabs/.github/.github/workflows/security-scan.yml@main
    with:
      language: 'go'
      go-version: '1.23.0'

  docker:
    name: Docker Build and Security
    needs: [test, security]
    if: github.event_name != 'pull_request'
    uses: loqalabs/.github/.github/workflows/docker-build-and-push.yml@main
    with:
      registry: docker.io
      image-name: loqalabs/loqa-hub
    secrets:
      docker-username: ${{ secrets.DOCKER_USERNAME }}
      docker-token: ${{ secrets.DOCKER_TOKEN }}
